routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\CourseController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\TopicController;
use App\Http\Controllers\Backend\LessonController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\CarouselController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\WelcomeController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__ . '/auth.php';

Route::get('/', [WelcomeController::class,'homepage'])->name('homepage');
Route::get('/caterories/{category}/courses', [WelcomeController::class, 'courseList'])->name('frontend.courses');
Route::get('/courses/{courses}', [WelcomeController::class, 'courseDetails'])->name('frontend.courses.show');
Route::get('/my-shopping-cart', [WelcomeController::class, 'shoppingCart'])->name('frontend.cart');
Route::get('remove-cart/{id}', [WelcomeController::class, 'removeCart'])->name('remove.cart');
Route::get('checkout/', [WelcomeController::class, 'checkout'])->name('checkout.cart');
// Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::post('/courses/{course}/comments', [CommentController::class, 'store'])->name('courses.comments.store');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    //courses
    Route::get('course/pdf', [CourseController::class, 'downloadPdf'])->name('course.pdf');
    Route::resource('courses', CourseController::class);
    //topics
    Route::resource('topics', TopicController::class);
    //lessons
    Route::resource('lessons', LessonController::class);



    //carousel
    Route::get('carousels/pdf', [CarouselController::class, 'downloadPdf'])->name('carousels.pdf');
    Route::get('carousels-trash', [CarouselController::class, 'trash'])->name('carousels.trash');
    Route::patch('carousels-trash/{id}', [CarouselController::class, 'restore'])->name('carousels.restore');
    Route::delete('carousels-trash/{id}', [CarouselController::class, 'delete'])->name('carousels.delete');
    Route::resource('carousels', CarouselController::class);
    //category
    Route::resource('categories', CategoryController::class);

    /* profile details route */
    Route::get('/profile/detail', [ProfileController::class, 'profileDetails'])->name('profile.detail');
    Route::get('/profile/edit', [ProfileController::class, 'profileEdit'])->name('profile.edit');
    /* user */
    Route::get('/user', [UserController::class, 'index'])->name('users.index');
    Route::get('/user/{user}', [UserController::class, 'show'])->name('users.show');
    Route::get('/user/{user}/change-role', [UserController::class, 'changeRole'])->name('users.change_role');
    Route::patch('/user/{user}/change-role', [UserController::class, 'updateRole'])->name('users.update_role');

    Route::post('courses/{course}/cart', [CartController::class, 'store'])->name('courses.cart.store');
});
Route::fallback(function () {
    echo "Apnar Url Thik nai";
});

app/Http/Controllers/Backend/CarouselController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use App\Models\Carousel;
use Image;
use Pdf;
use Illuminate\Http\Request;

class CarouselController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $carousels = Carousel::all();
        return view('backend.carousels.index', compact('carousels'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.carousels.create');
    }

    public function store(Request $request)
    {
        $data = [
            'name' => $request->name,
            'is_active' => $request->is_active ? true : false,
            'image' =>  $this->uploadImage($request->file('image'))
        ];

        Carousel::create($data);

        return redirect()
            ->route('carousels.index')
            ->withMessage('Created Successfully!');
    }

    public function edit(Carousel $carousel)
    {
        return view('backend.carousels.edit', compact('carousel'));
    }

    public function update(Request $request, Carousel $carousel)
    {
        $data = [
            'name' => $request->name,
            'is_active' => $request->is_active ? true : false,
        ];

        if ($request->hasFile('image')) {
            $data['image'] = $this->uploadImage($request->file('image'));
        }

        $carousel->update($data);

        return redirect()
            ->route('carousels.index')
            ->withMessage('Updated Successfully!');
    }

    public function show(Carousel $carousel)
    {
        return view('backend.carousels.show', compact('carousel'));
    }

    public function destroy(Carousel $carousel)
    {
        $carousel->delete();
        return redirect()
            ->route('carousels.index')
            ->withMessage('Deleted Successfully!');
    }

    public function trash()
    {
        $carousels = Carousel::onlyTrashed()->get();
        return view('backend.carousels.trash', compact('carousels'));
    }

    public function restore($id)
    {
        $carousel = Carousel::onlyTrashed()->find($id);
        $carousel->restore();

        return redirect()
            ->route('carousels.trash')
            ->withMessage('Restored Successfully!');
    }

    public function delete($id)
    {
        $carousel = Carousel::onlyTrashed()->find($id);
        $carousel->forceDelete();

        return redirect()
            ->route('carousels.trash')
            ->withMessage('Deleted Successfully!');
    }

    public function downloadPdf()
    {
        $carousels = Carousel::all();
        $pdf = Pdf::loadView('backend.carousels.pdf', compact('carousels'));
        return $pdf->stream('carousel-list.pdf');
    }

    public function uploadImage($file)
    {
        $fileName = date('y-m-d').'-'.time().'.'.$file ->getClientOriginalExtension();
        // $file->move(storage_path('app/public/carousels'), $fileName);

        Image::make($file)
                ->resize(1600, 500)
                ->save(storage_path() . '/app/public/carousels/' . $fileName);

        return $fileName;
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->get();
        // return view('categories.index',[
        //     'categories'=> $categories
        // ]);

        return view('backend.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = [
            'title' => $request->title,
            'Description' => $request->Description,
            'is_active' => $request->is_active ? true : false,
        ];

        Category::create($requestData);

        return redirect()
            ->route('categories.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        // dd($category);
        return view('backend.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        // $category = Category::find($id);
        return view('backend.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // $category = Category::find($id);

        $requestData = [
            'title' => $request->title,
            'Description' => $request->Description,
            'is_active' => $request->is_active ? true : false,
        ];



        $category->update($requestData);

        return redirect()
            ->route('categories.index')
            ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            // dd('$id');
            $category = Category::find($id);
            $category->delete();
            // Session::flush('message', 'Successfully Deleted');
            return redirect()
                ->route('categories.index')
                ->with('message', 'Successfully Deleted');
    }
}

app/Http/Controllers/Backend/CourseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Course;
use App\Models\Topic;
use Str;
use Image;
use Pdf;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::all();
        return view('backend.course.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('title', 'id')->toArray();
        $topic = Topic::pluck('name', 'id')->toArray();
        return view('backend.course.create', compact('categories', 'topic'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = [
            'slug' => Str::slug($request->title),
            'category_id' => $request->category_id,
            'title' => $request->title,
            'description' => $request->description,
            'price' => $request->price,
            'is_active' => $request->is_active ? true : false,
            'topic_id' => $request->topic_id,
            'image' =>  $this->uploadImage($request->file('image'))
        ];

        $course = Course::create($requestData);


        return redirect()
            ->route('courses.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Course $course)
    {
        return view('backend.course.show', compact('course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course)
    {
        $categories = Category::pluck('title', 'id')->toArray();
        $topics = Topic::pluck('name', 'id')->toArray();
        return view('backend.course.edit', compact('course', 'categories', 'topics'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course)
    {
        $requestData = [
            'title' => $request->title,
            'category_id' => $request->category_id,
            'description' => $request->description,
            'price' => $request->price,
            'is_active' => $request->is_active ? true : false,

        ];
        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }
        $course->update($requestData);
        return redirect()
            ->route('courses.index')
            ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Course $course)
    {
        $course->delete();
        return redirect()
            ->route('courses.index')
            ->withMessage('Successfully deleted');
    }
    public function uploadImage($file)
    {
        $fileName = date('y-m-d').'-'.time().'.'.$file ->getClientOriginalExtension();
        // $file->move(storage_path('app/public/carousels'), $fileName);

        Image::make($file)
                ->resize(400, 500)
                ->save(storage_path() . '/app/public/courses/' . $fileName);

        return $fileName;
    }
    public function downloadPdf()
    {
        $courses = Course::all();
        // dd($courses);
        $pdf = Pdf::loadView('backend.Course.pdf', compact('courses'));
        return $pdf->stream('course-list.pdf');
    }

}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard.index');
    }

}

app/Http/Controllers/Backend/LessonController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\lesson;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lesson = lesson::all();
        return view('backend.lesson.index', compact('lesson'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.lesson.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = [
            // 'lesson_id' => $request->lesson_id,
            'name' => $request->name,
            'description' => $request->description,

            'is_active' => $request->is_active ? true : false,

        ];

        $lesson = lesson::create($requestData);


        return redirect()
            ->route('lessons.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(lesson $lesson)
    {
        return view('backend.lesson.show', compact('lesson'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(lesson $lesson)
    {
        return view('backend.lesson.edit', compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, lesson $lesson)
    {
        $requestData = [
            'name' => $request->name,
            // 'category_id' => $request->lesson_id,
            'description' => $request->description,
            'is_active' => $request->is_active ? true : false,

        ];
        $lesson->update($requestData);
        return redirect()
        ->route('lessons.index')
        ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(lesson $lesson)
    {
        $lesson->delete();



        return redirect()
            ->route('lessons.index')
            ->withMessage('Successfully deleted');

    }
}

resources/views/backend/course/create.blade.php
<x-master>
    <x-slot:title>
        {{ __('Course Create') }}
        </x-slot>


        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ __('Courses') }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('courses.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        {{ __('List') }}
                    </button>
                </a>
            </div>
        </div>

        <form action="{{ route('courses.store') }}" method="post" enctype="multipart/form-data">
            @csrf


            <x-forms.input type="text" name="title" placeholder="Enter title" required label="Title" />

            <x-forms.select name="category_id" required label="Category" :options="$categories" />
            <x-forms.select name="topic_id" required label="Topic" :options="$topic" />
            <x-forms.input type="number" name="price" placeholder="Enter price" required label="Price" />
            <x-forms.input type="file" name="image" label="Image"/>

            <x-forms.textarea name="description" label="Description" id="description"/>

            @php
                $checklist = ['1' => 'Is Active'];
            @endphp

            <x-forms.checkbox name="is_active" id="is_active" :checklist="$checklist" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</x-master>

resources/views/backend/course/edit.blade.php
<x-master>
    <x-slot:title>
        Course Create
        </x-slot>

        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ __('Courses') }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('courses.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        {{ __('List') }}
                    </button>
                </a>
            </div>
        </div>

        <form action="{{ route('courses.update', $course->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')

            <x-forms.input type="text" name="title" :value="old('title', $course->title)" placeholder="Enter title" required
                label="Title" />

           

            <x-forms.select name="category_id" required label="Category" :selected="old('category_id', $course->category_id)" :options="$categories" />
            <x-forms.select name="topic_id" required label="Topic" :selected="old('topic_id', $course->topic_id)" :options="$topics" />
            <x-forms.input type="file" name="image" label='Picture' />

            <x-forms.textarea name="description" label="Description" :value="old('description', $course->description)" id="description"/>



            @php
                $checklist = ['1' => 'Is Active'];

                $checkedItems = [$course->is_active];

            @endphp

            <x-forms.checkbox name="is_active" id="is_active" :checklist="$checklist" :checkedItems="$checkedItems" />

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</x-master>

resources/views/backend/course/index.blade.php
<x-master>
    <x-slot:title>
        Course List
        </x-slot>

        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Courses</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('course.pdf') }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary">PDF</button>
                    </a>
                </div>
                <a href="{{ route('courses.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                    <th width="180">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($courses as $course)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $course->title }}</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="{{ route('courses.show', $course->id) }}">Show</a>
                            <a class="btn btn-sm btn-warning" href="{{ route('courses.edit', $course->id) }}">Edit</a>
                            <form action="{{ route('courses.destroy', $course->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-sm btn-danger"
                                    onclick="return confirm('Are you sure want to delete')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{-- $courses->links() --}}
</x-master>

resources/views/backend/course/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($courses as $course)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $course->title }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/backend/course/show.blade.php
 <x-master>
    <x-slot:title>
        Course Details
    </x-slot>
    
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Course</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('courses.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <p>course: {{ $course->course?->title }}</p>
    <h1>Title: {{ $course->title }}</h1>
    <p>Price:{{ $course->price }}</p>
    <p>Description:{{ $course->description }}</p>
    <img src="{{ asset('storage/courses/'.$course->image) }}" />

    

    <p>Is Active ?: {{ $course->is_active ? 'Yes' : 'No' }}</p>

</x-master>

resources/views/backend/course/trash.blade.php
<x-master>
    <x-slot:title>
        {{ __('course List') }}
    </x-slot>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ __('courses Trash') }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('courses.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    {{ __('List') }}
                </button>
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>{{ __('SL#') }}</th>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Action') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($courses as $course)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $course->title }}</td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ route('courses.show', $course->id) }}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('courses.restore', $course->id) }}">Restore</a>
                    <form action="{{ route('courses.delete', $course->id) }}" method="post" style="display:inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure want to delete')" title="Permanent Delete">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</x-master>